VIDEOS= RMS-W1_V1.ogv RMS-W1_V2.ogv RMS-W1_V3.ogv
RM=rm -f
WGET=wget

all: $(VIDEOS)

RMS-W1_V1.ogv:
	$(WGET) http://vrepin.org/rms/W1/RMS-W1_V1.ogv

RMS-W1_V2.ogv:
	$(WGET) http://vrepin.org/rms/W1/RMS-W1_V2.ogv

RMS-W1_V3.ogv:
	$(WGET) http://vrepin.org/rms/W1/RMS-W1_V3.ogv


clean:
	$(RM) $(VIDEOS)
