VIDEOS=RMS-W5-D1.ogv RMS-W5-D2.ogv RMS-W5-D3.ogv RMS-W5-D4.ogv RMS-W5-D5.ogv

RM=rm -f
WGET=wget
URL_ROOT=http://vrepin.org/rms/W5/

all: $(VIDEOS)

RMS-W5-D1.ogv:
	$(WGET) $(URL_ROOT)$@

RMS-W5-D2.ogv:
	$(WGET) $(URL_ROOT)$@

RMS-W5-D3.ogv:
	$(WGET) $(URL_ROOT)$@

RMS-W5-D4.ogv:
	$(WGET) $(URL_ROOT)$@

RMS-W5-D5.ogv:
	$(WGET) $(URL_ROOT)$@


clean:
	$(RM) $(VIDEOS)
