VIDEOS=RMS-W4-D1.ogv RMS-W4-D2.ogv RMS-W4-D3.ogv RMS-W4-D4.ogv


RM=rm -f
WGET=wget
URL_ROOT=http://vrepin.org/rms/W4/


all: $(VIDEOS)

RMS-W4-D1.ogv:
	$(WGET) $(URL_ROOT)$@

RMS-W4-D2.ogv:
	$(WGET) $(URL_ROOT)$@

RMS-W4-D3.ogv:
	$(WGET) $(URL_ROOT)$@

RMS-W4-D4.ogv:
	$(WGET) $(URL_ROOT)$@

clean:
	$(RM) $(VIDEOS)
